-- ==========================================
-- 1. Создание таблиц (Безопасно)
-- ==========================================

CREATE TABLE IF NOT EXISTS role (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    CONSTRAINT chk_role_name CHECK (name IN ('User', 'Admin'))
);

CREATE TABLE IF NOT EXISTS colorscheme (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL UNIQUE,
    color character varying(7) NOT NULL,
    theme character varying(10) DEFAULT 'light' NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_theme CHECK (theme IN ('light', 'dark'))
);

CREATE TABLE IF NOT EXISTS currency (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character(3) NOT NULL UNIQUE,
    name character varying(50) NOT NULL,
    symbol character varying(10) NOT NULL,
    nominal integer DEFAULT 1,
    icon_url character varying(255),
    is_crypto boolean DEFAULT false,
    is_popular boolean DEFAULT false,
    sort_order integer DEFAULT 999
);

CREATE TABLE IF NOT EXISTS operationtype (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS notificationtype (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL UNIQUE,
    send_email boolean DEFAULT false,
    send_push boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "user" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id integer DEFAULT 1 NOT NULL,
    login character varying(50) NOT NULL UNIQUE,
    name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(100) NOT NULL UNIQUE,
    is_premium boolean DEFAULT false,
    currency_id integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "ColorScheme_id" integer
);

CREATE TABLE IF NOT EXISTS blacklisted_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    name character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    color character varying(7) DEFAULT '#4ECDC4',
    CONSTRAINT category_user_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS operation (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    category_id integer,
    operation_type_id integer NOT NULL,
    description text,
    amount numeric(13,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    custom_category character varying(255)
);

CREATE TABLE IF NOT EXISTS premiumuser (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL UNIQUE,
    subscription_end timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spendinglimit (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    amount numeric(13,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_limit_user_category UNIQUE (user_id, category_id)
);

CREATE TABLE IF NOT EXISTS notification (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    type_id integer NOT NULL,
    message text NOT NULL,
    source character varying(10) NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    scheduled_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exchange_rate (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_id integer NOT NULL,
    rate numeric(10,4) NOT NULL,
    previous_rate numeric(10,4),
    change_amount numeric(10,4) DEFAULT 0.0000,
    change_percentage numeric(6,3) DEFAULT 0.000,
    date date NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_currency_date UNIQUE (currency_id, date)
);


-- ==========================================
-- 2. Безопасное добавление внешних ключей
-- ==========================================
-- Используем DO $$ ... $$ блок, чтобы проверять существование ключа перед добавлением.
-- Это гарантирует отсутствие ошибок при повторном запуске.

DO $$ 
BEGIN
    -- User -> Role
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_role') THEN
        ALTER TABLE "user" ADD CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role(id);
    END IF;

    -- User -> Currency
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_currency') THEN
        ALTER TABLE "user" ADD CONSTRAINT fk_user_currency FOREIGN KEY (currency_id) REFERENCES currency(id);
    END IF;

    -- User -> ColorScheme
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_colorscheme') THEN
        ALTER TABLE "user" ADD CONSTRAINT fk_user_colorscheme FOREIGN KEY ("ColorScheme_id") REFERENCES colorscheme(id) ON DELETE SET NULL;
    END IF;

    -- Category -> User
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_category_user') THEN
        ALTER TABLE category ADD CONSTRAINT fk_category_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
    END IF;

    -- Operation -> User
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operation_user') THEN
        ALTER TABLE operation ADD CONSTRAINT fk_operation_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
    END IF;

    -- Operation -> Category
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operation_category') THEN
        ALTER TABLE operation ADD CONSTRAINT fk_operation_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE;
    END IF;

    -- Operation -> OperationType
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_operation_type') THEN
        ALTER TABLE operation ADD CONSTRAINT fk_operation_type FOREIGN KEY (operation_type_id) REFERENCES operationtype(id) ON DELETE RESTRICT;
    END IF;

    -- PremiumUser -> User
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_premium_user') THEN
        ALTER TABLE premiumuser ADD CONSTRAINT fk_premium_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
    END IF;

    -- SpendingLimit -> User
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_spending_user') THEN
        ALTER TABLE spendinglimit ADD CONSTRAINT fk_spending_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
    END IF;

    -- SpendingLimit -> Category
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_spending_category') THEN
        ALTER TABLE spendinglimit ADD CONSTRAINT fk_spending_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE;
    END IF;

    -- Notification -> User
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notification_user') THEN
        ALTER TABLE notification ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
    END IF;

    -- Notification -> NotificationType
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notification_type') THEN
        ALTER TABLE notification ADD CONSTRAINT fk_notification_type FOREIGN KEY (type_id) REFERENCES notificationtype(id) ON DELETE CASCADE;
    END IF;

    -- ExchangeRate -> Currency
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_exchange_currency') THEN
        ALTER TABLE exchange_rate ADD CONSTRAINT fk_exchange_currency FOREIGN KEY (currency_id) REFERENCES currency(id) ON DELETE CASCADE;
    END IF;

END $$;


-- ==========================================
-- 3. Индексы (Безопасно)
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_blacklisted_expires_at ON blacklisted_tokens USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_blacklisted_token_prefix ON blacklisted_tokens USING btree ("substring"(token, 1, 255));

CREATE INDEX IF NOT EXISTS idx_exchange_currency_id ON exchange_rate USING btree (currency_id);
CREATE INDEX IF NOT EXISTS idx_exchange_date ON exchange_rate USING btree (date);